version: '3.7'

services:
  postgres-db:
    image: stealthy-kratos-storage:latest
    build:
      context: .
      target: kratos_storage
    env_file:
      - postgres.env
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  kratos:
    image: stealthy-kratos:latest
    build:
      context: .
      target: kratos_application
    ports:
      - "4434:4434"
    env_file:
      - kratos.env
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4434/health/ready || exit 1
      retries: 3
      timeout: 3s
      interval: 10s
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres-data-dev:
